part of '../screens/chess_analysis_page.dart';

const List<BotCharacter> _botCharacters = <BotCharacter>[
  BotCharacter(
    rank: 1,
    name: 'Mochi Gearheart',
    description: 'I just wanted to see the pretty wooden pieces...',
    elo: 100,
    limitStrength: true,
    multiPv: 20,
    threads: 1,
    skillLevel: 0,
    searchDepth: 1,
    moveTimeMs: 800,
    profile: BotSkillProfile.baby,
    avatarAsset: 'assets/bots/hammy.png',
  ),
  BotCharacter(
    rank: 2,
    name: 'Checkmate Carl',
    description: 'Mate in three? 👍.',
    elo: 450,
    limitStrength: true,
    multiPv: 8,
    threads: 1,
    skillLevel: 2,
    searchDepth: 2,
    moveTimeMs: 500,
    profile: BotSkillProfile.nephew,
    avatarAsset: 'assets/bots/ok.png',
  ),
  BotCharacter(
    rank: 3,
    name: 'Rex Halfcheck',
    description:
        'Do you even lift (your pieces), bro? I\'m going to crush your center like it\'s leg day.',
    elo: 800,
    limitStrength: true,
    multiPv: 3,
    threads: 1,
    skillLevel: 8,
    searchDepth: 6,
    moveTimeMs: 900,
    profile: BotSkillProfile.teenBoy,
    avatarAsset: 'assets/bots/doggo.png',
  ),
  BotCharacter(
    rank: 4,
    name: 'Octavian Inkveil',
    description:
        'Oh, please. Your opening is so unrefined. Witness true brilliance.',
    elo: 1150,
    limitStrength: true,
    multiPv: 3,
    threads: 2,
    skillLevel: 12,
    searchDepth: 10,
    moveTimeMs: 1000,
    profile: BotSkillProfile.grandpa,
    avatarAsset: 'assets/bots/goodlooking.png',
  ),
  BotCharacter(
    rank: 5,
    name: 'Master Prime',
    description: 'The engine predicted your defeat ten moves ago.',
    elo: 1500,
    limitStrength: true,
    multiPv: 2,
    threads: 2,
    skillLevel: 16,
    searchDepth: 14,
    moveTimeMs: 1200,
    profile: BotSkillProfile.interGm,
    avatarAsset: 'assets/bots/chudmaster.png',
  ),
];
