import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:ui' as ui;

import 'package:audioplayers/audioplayers.dart';
import 'package:chessiq/core/providers/economy_provider.dart';
import 'package:chessiq/core/services/ad_service.dart';
import 'package:chessiq/core/services/engine_service.dart';
import 'package:chessiq/core/services/purchase_service.dart';
import 'package:chessiq/core/theme/app_theme_provider.dart';
import 'package:chessiq/features/academy/screens/puzzle_map_screen.dart';
import 'package:chessiq/features/analysis/models/analysis_models.dart';
import 'package:chessiq/features/analysis/painters/energy_arrow_painter.dart';
import 'package:chessiq/features/quiz/models/quiz_models.dart';
import 'package:chessiq/features/quiz/painters/quiz_accuracy_trend_painter.dart';
import 'package:chessiq/features/store/models/store_models.dart';
import 'package:chessiq/features/vs_bot/models/vs_bot_models.dart';
import 'package:chessiq/shared/widgets/theme_selector_tiles.dart';
import 'package:chessiq/shared/widgets/universal_settings_sheet.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

part '../chess_analysis/base_state.dart';
part '../chess_analysis/bot_roster.dart';
part '../chess_analysis/page.dart';
part '../chess_analysis/page_shared.dart';
part '../../quiz/mixins/quiz_components_mixin.dart';
part '../../quiz/models/quiz_round_review.dart';
part '../../quiz/mixins/quiz_screen_mixin.dart';
