import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:ui' as ui;

import 'package:audioplayers/audioplayers.dart';
import 'package:chessiq/core/providers/economy_provider.dart';
import 'package:chessiq/core/services/ad_service.dart';
import 'package:chessiq/core/services/engine_service.dart';
import 'package:chessiq/core/services/purchase_service.dart';
import 'package:chessiq/core/theme/app_theme_provider.dart';
import 'package:chessiq/features/academy/screens/puzzle_map_screen.dart';
import 'package:chessiq/features/analysis/models/analysis_models.dart';
import 'package:chessiq/features/analysis/painters/energy_arrow_painter.dart';
import 'package:chessiq/features/quiz/data/opening_quiz_catalog.dart';
import 'package:chessiq/features/quiz/models/quiz_models.dart';
import 'package:chessiq/features/quiz/painters/quiz_accuracy_trend_painter.dart';
import 'package:chessiq/features/store/models/store_models.dart';
import 'package:chessiq/features/vs_bot/models/bot_lines.dart';
import 'package:chessiq/features/vs_bot/models/bot_roster.dart';
import 'package:chessiq/features/vs_bot/models/vs_bot_models.dart';
import 'package:chessiq/shared/widgets/theme_selector_tiles.dart';
import 'package:chessiq/shared/widgets/universal_settings_sheet.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

part '../../quiz/core/quiz_academy_surface.dart';
part '../../quiz/core/quiz_components.dart';
part '../../quiz/core/quiz_screen.dart';
part '../../quiz/core/quiz_study_screen.dart';
part '../../quiz/models/quiz_round_review.dart';
part '../../store/screens/store.dart';
part '../../vs_bot/core/vs_bot_core.dart';
part '../../vs_bot/models/ghost_arrow.dart';
part '../../vs_bot/screens/vs_bot.dart';
part '../chess_analysis/base_state.dart';
part '../chess_analysis/page.dart';
part '../chess_analysis/page_shared.dart';

const List<BotCharacter> _botCharacters = botRoster;
