platform :ios, '15.0'

use_modular_headers!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', 'Debug' => :debug, 'Profile' => :release, 'Release' => :release

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end

  flutter_root = ENV['FLUTTER_ROOT']
  if flutter_root.nil? || flutter_root.empty?
    flutter_bin = `which flutter`.strip
    if flutter_bin.empty?
      raise 'Could not find flutter executable. Set FLUTTER_ROOT or install Flutter.'
    end
    flutter_root = File.expand_path('..', File.dirname(flutter_bin))
  end

  flutter_root
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)
end
